server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    rewrite ^/docs$ /docs/guide/install-build permanent;
    rewrite ^/docs/guide$ /docs/guide/install-build permanent;
}
